# Generated by Django 4.2.30 on 2026-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='광고 제목')),
                ('description', models.TextField(blank=True, verbose_name='광고 내용')),
                ('latitude', models.FloatField(verbose_name='위도 (Latitude)')),
                ('longitude', models.FloatField(verbose_name='경도 (Longitude)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
    ]
